server:
  port: 8082
  servlet:
    context-path: /customer

spring:
  application:
    name: customer-service
  banner:
    location: tiger-banner.txt
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_CONNECTION:localhost:9092}
    topic-send-message-inbound: send-message-inbound
    producer:
      bootstrap-servers: ${KAFKA_CONNECTION:localhost:9092}
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000
  profiles:
    active: dev

jwt:
  singer-key: ${JWT_SECRET_KEY}

grpc:
  server:
    port: 9099