server:
  port: 8082
  servlet:
    context-path: /customer

spring:
  application:
    name: customer-service
  banner:
    location: tiger-banner.txt
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
  profiles:
    active: dev

jwt:
  singer-key: ${JWT_SECRET_KEY}